### ISSUE TITLE
Game breaks thru framerate limit

### ISSUE THREAD

**Issue by ewbteewbte** [flightlessmango/MangoHud#127] opened 2020-04-13 08:38 UTC
So I have 48 fps frame rate limit in my config file and it works as intended in Dark Souls Remastered and Dark Souls SotFS. Today I noticed that when I play Tomb Raider 2013 with proton 4.11.13 the cap works, but at some point it stops to work and it turn on again only if I go to main menu or die in the game.

Also "mangohud %command%" doesn't seem to work with OpenGL 
I am running Pop!_OS 19.10

Thanks

**Comment by jackun** [comment] 2020-04-13 09:36
> Also "mangohud %command%" 

Because it is a 32bit executable.

Are you using `fps_limit` (shouldn't just stop working :thinking: ) or v-sync "divider"?

**Comment by ewbteewbte** [comment] 2020-04-13 13:09
yep I use `fps_limit=48` and vsync is turned off.
I am trying to have smooth performance while maintaining low temps and silence :)

**Comment by flightlessmango** [comment] 2020-04-15 05:53
@ewbteewbte 
> at some point it stops to work

Could you give steps to replicate this?

**Comment by ewbteewbte** [comment] 2020-04-15 07:56
> @ewbteewbte
> 
> > at some point it stops to work
> 
> Could you give steps to replicate this?

As I remember, for the first time it happened almost in the beginning of the game, where you a get tutorial for a "silent kill" (about 30min into the game) and then the whole place gets on fire.

Otherwise I can try to enable Log in conf file and then drop it here. Will that help?

**Comment by flightlessmango** [comment] 2020-05-23 20:01
Are you still able to reproduce this?

**Comment by flightlessmango** [comment] 2020-07-04 04:52
closing since it's unknown if this is still an issue

**Comment by ewbteewbte** [comment] 2020-09-29 19:59
well. the issue appeared again in Hollow Knight, fps limit turns off just after a couple of minutes of gaming, I can't spot any particular steps which can lead to this, it just happens, alt+tab may have its part in that glitch. 
Linux PopOS 20.04 Steam Hollow Knight Native Linux Version. 3400g Vega 11 APU with latest Kisak Mesa drivers (recommended by Steam afaik)

Thanks, meanwhile mangohud is awesome and I have zero issues with Vulkan.

**Comment by flightlessmango** [comment] 2020-09-30 04:36
Here is a modified version that shows the framerate limit on the hud [mangohud-fps.tar.gz](flightlessmango.com/mangohud-fps.tar.gz), I'm interested to know if the literal limit is being changed somehow or if it stops working all together. Should show `inf` if there is no limit

**Comment by ewbteewbte** [comment] 2020-10-20 17:40
Hey, I wasn't able to download the file you provided. And I also faced the same issue with another native Linux OpenGL game called FEZ. So with what I noticed it happens when an in-game scene changes (going to pause menu and back counts as well) and it is only happens with OpenGL. Never had any issues with DXVK or Vulkan games (based on what MangoHud says in a hud).

**Comment by ewbteewbte** [comment] 2020-10-30 15:17
So, I assembled an absolutely new PC, made a fresh install of Pop!_OS 20.04, built MangoHud and.. yep, the issue is still there, damn FEZ is running at THOUSAND fps and my GPU transistors scream so much lol.

**Comment by flightlessmango** [comment] 2020-10-31 09:14
Are you using native or proton with Fez?

**Comment by ewbteewbte** [comment] 2020-10-31 16:19
As I said, it happens with native versions, which use OpenGL. No issues with fps limit on proton versions. I would stick with proton, but some of the native versions of games run like twice smoother with less input lag, for example Hollow Knight.

**Comment by flightlessmango** [comment] 2020-11-01 15:51
I tried again with native Fez and I was still not able to replicate this behavior

**Comment by flgx16** [comment] 2020-11-01 22:06
I had this issue already in older MangoHud version and talked about it on Discord but then it seemed to be fixed (both OpenGL and Vulkan was affected I think)

Tested Minecraft (with mods which change rendering) with fps_limit set to 160 and it stopped limiting FPS after 2-3 minutes in this video. Seems like it happened right as I jumped but I was also jumping before
Maybe worth noting that I alt-tabbed few times and resized the window when I started the game

Not sure if it happens with Vulkan currently but I had it happen it multiple times in native OpenGL games

Video: https://www.dropbox.com/s/9m824ji0rpa0ore/minecraft_mangohud_fps_limit.mkv?dl=0

MangoHud 0.5.1

**Comment by ewbteewbte** [comment] 2020-11-02 01:42
Oh wait, yes, I alt+tab a lot, all the time.

**Comment by flightlessmango** [comment] 2020-11-02 08:20
I never alt+tab as it doesn't exist as a concept in i3, that could be the thing

**Comment by ewbteewbte** [comment] 2020-11-07 03:38
flgx16 how to use it? It just happened with a Hollow Knight running with proton DXVK, so not only with OpenGL native games.

**Comment by flgx16** [comment] 2020-11-07 12:52
You can build `develop` branch with my patch:
`git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git -b develop`
`cd MangoHud`
`wget https://patch-diff.githubusercontent.com/raw/flightlessmango/MangoHud/pull/376.patch`
`patch -Np1 < 376.patch`
`./build.sh install`

Or here's my build: [MangoHud-package.zip](https://github.com/flightlessmango/MangoHud/files/5504747/MangoHud-package.zip)

**Comment by ewbteewbte** [comment] 2020-11-07 20:58
Thank you! Weird, I built your version, and it works in Dark Souls 3 but in Hollow Knight hud itself doesn't show up at all.

**Comment by flightlessmango** [comment] 2020-11-14 07:40
This is "fixed" as in it still *can* happen, but it seems to be fixing itself. Unsure if this can be closed or not

**Closed by flightlessmango** 2020-11-14 07:40 UTC
