### ISSUE TITLE
MangoHud always displays Throttling Power

### ISSUE THREAD

**Issue by fuzunspm** [flightlessmango/MangoHud#748] opened 2022-05-06 20:18 UTC
Even with very very low load it always displays `Throttling Power`

Below screenshot was taken from a main menu with fps limit set to 60. it should not display the throttling power text here. It also displays Temp text from time to time for half a second but my gpu temps never exceeds 58 C degree

![image](https://user-images.githubusercontent.com/12132746/167210882-7fb178ef-f7e1-47df-bad0-c8215d490adf.png)

**Comment by flightlessmango** [comment] 2022-05-07 09:46
Is it nvidia or amd?

**Comment by fuzunspm** [comment] 2022-05-07 10:11
Both are amd 
R5 2600
6700XT

**Comment by flightlessmango** [comment] 2022-05-07 10:13
Throttling is only for GPU currently. How are you verifying that you're not actually power throttled?

**Comment by fuzunspm** [comment] 2022-05-07 10:26
Total power draw is almost half of what I got. Other than that I don’t understand how main menu or even limited glxgears could cause power throttling. I don’t have performance problems in games either

**Comment by flightlessmango** [comment] 2022-05-07 11:32
A power throttling case is lowering the power to save on power in low use scenarios

**Comment by flightlessmango** [comment] 2022-05-09 16:25
I can't say it's not normal behavior, but I am fairly sure that there isn't a bug in mangohud. I'm leaning towards it being normal or there is a bug in the amdgpu kernel driver

**Comment by rowbawts** [comment] 2022-05-09 19:18
> I can't say it's not normal behavior, but I am fairly sure that there isn't a bug in mangohud. I'm leaning towards it being normal or there is a bug in the amdgpu kernel driver

Yeah I'm not sure either as I've only ever used this card in this OS so since I have nothing to compare against I wouldn't know if it's impeding my performance but as everything I run works great it's fine just a curious thing I noticed.

**Comment by nyan1337** [comment] 2022-08-12 15:07
Same problem with a RX 6700 XT
Both throttling power & temp showing even in menu screens

**Comment by Daniel-Salvado** [comment] 2022-10-14 20:36
> Same problem with a RX 6700 XT Both throttling power & temp showing even in menu screens

Exactly the same here with a RX 6750 XT. Fedora 36 Kernel 5.19.15.

**Comment by MCPO-Spartan-117** [comment] 2023-01-02 02:15
5.12.19 showed it like expected, 6.1.2 always shows it.

**Comment by Dim-P** [comment] 2023-01-15 20:53
Same here, RX 6600 on Nobara (kernel `6.0.14`).

**Comment by flightlessmango** [comment] 2023-01-16 14:44
I have no reason to believe this is an issue with mangohud and rather an amdgpu issue.
It would be great if someone could make an issue over there https://gitlab.freedesktop.org/drm/amd/-/issues

**Comment by barokvanzieks** [comment] 2023-02-09 22:00
happens on an rtx 3050ti laptop too

**Comment by awsms** [comment] 2023-03-25 15:41
> happens on an rtx 3050ti laptop too

same with rtx3060 laptop

**Comment by mrphs7019** [comment] 2023-07-14 08:04
same with rtx3060 laptop

**Comment by Umio-Yasuno** [comment] 2023-07-27 07:43
I have created an issue in drm/amd for this issue.

https://gitlab.freedesktop.org/drm/amd/-/issues/2720

**Comment by Umio-Yasuno** [comment] 2023-07-27 10:12
AMDGPU patch for Navi22/Navi23/Navi24.
But I tested only on Navi23.  

```diff
diff --git a/.//drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c b/home/coelacanth/src/linux-kernel/linux-6.4.2/drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c
index 85d53597e..548d25cf3 100644
--- a/.//drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c
+++ b/home/coelacanth/src/linux-kernel/linux-6.4.2/drivers/gpu/drm/amd/pm/swsmu/smu11/sienna_cichlid_ppt.c
@@ -578,7 +578,9 @@ static int sienna_cichlid_tables_init(struct smu_context *smu)
 	return -ENOMEM;
 }
 
-static uint32_t sienna_cichlid_get_throttler_status_locked(struct smu_context *smu)
+static uint32_t sienna_cichlid_get_throttler_status_locked(struct smu_context *smu,
+							   bool use_metrics_v3,
+							   bool use_metrics_v2)
 {
 	struct smu_table_context *smu_table= &smu->smu_table;
 	SmuMetricsExternal_t *metrics_ext =
@@ -586,13 +588,11 @@ static uint32_t sienna_cichlid_get_throttler_status_locked(struct smu_context *s
 	uint32_t throttler_status = 0;
 	int i;
 
-	if ((smu->adev->ip_versions[MP1_HWIP][0] == IP_VERSION(11, 0, 7)) &&
-	     (smu->smc_fw_version >= 0x3A4900)) {
+	if (use_metrics_v3) {
 		for (i = 0; i < THROTTLER_COUNT; i++)
 			throttler_status |=
 				(metrics_ext->SmuMetrics_V3.ThrottlingPercentage[i] ? 1U << i : 0);
-	} else if ((smu->adev->ip_versions[MP1_HWIP][0] == IP_VERSION(11, 0, 7)) &&
-	     (smu->smc_fw_version >= 0x3A4300)) {
+	} else if (use_metrics_v2) {
 		for (i = 0; i < THROTTLER_COUNT; i++)
 			throttler_status |=
 				(metrics_ext->SmuMetrics_V2.ThrottlingPercentage[i] ? 1U << i : 0);
@@ -854,7 +854,7 @@ static int sienna_cichlid_get_smu_metrics_data(struct smu_context *smu,
 			metrics->TemperatureVrSoc) * SMU_TEMPERATURE_UNITS_PER_CENTIGRADES;
 		break;
 	case METRICS_THROTTLER_STATUS:
-		*value = sienna_cichlid_get_throttler_status_locked(smu);
+		*value = sienna_cichlid_get_throttler_status_locked(smu, use_metrics_v3, use_metrics_v2);
 		break;
 	case METRICS_CURR_FANSPEED:
 		*value = use_metrics_v3 ? metrics_v3->CurrFanSpeed :
@@ -4056,7 +4056,7 @@ static ssize_t sienna_cichlid_get_gpu_metrics(struct smu_context *smu,
 	gpu_metrics->current_dclk1 = use_metrics_v3 ? metrics_v3->CurrClock[PPCLK_DCLK_1] :
 		use_metrics_v2 ? metrics_v2->CurrClock[PPCLK_DCLK_1] : metrics->CurrClock[PPCLK_DCLK_1];
 
-	gpu_metrics->throttle_status = sienna_cichlid_get_throttler_status_locked(smu);
+	gpu_metrics->throttle_status = sienna_cichlid_get_throttler_status_locked(smu, use_metrics_v3, use_metrics_v2);
 	gpu_metrics->indep_throttle_status =
 			smu_cmn_get_indep_throttler_status(gpu_metrics->throttle_status,
 							   sienna_cichlid_throttler_map);
```

**Comment by Umio-Yasuno** [comment] 2023-08-24 10:17
The AMDGPU patch has been merged into Linux Kernel v6.1.47 and v6.4.12 .

**Comment by czak** [comment] 2023-08-25 08:08
Thank you @Umio-Yasuno :tada: I can confirm throttling indicators disappeared on 6.1.47 for me (6600XT).

![image](https://github.com/flightlessmango/MangoHud/assets/14021/fd0e04ca-883b-4d61-a22e-c3ca21b0d8f7)

**Closed** 2023-08-25 15:03 UTC

**Comment by awsms** [comment] 2023-09-20 00:41
@mrphs7019 @youmukonpaku1337 i assume you guys are still experiencing too?

**Comment by youmukonpaku1337** [comment] 2023-09-20 06:50
yeep i am

**Comment by awsms** [comment] 2023-09-20 14:50
I'm nowhere near as good as yasuno when it comes to programming, so I'd have no idea what to patch in the nvidia-drm module. if someone experienced with NVIDIA's stuff wants to have a look at it....

**Comment by mrphs7019** [comment] 2023-09-24 06:34
@awsms idk i deleted mangohud

**Comment by awsms** [comment] 2023-10-13 21:26
@mrphs7019 @youmukonpaku1337 the reason was... my vBIOS is throttled to 80W on Linux. i flashed a vBIOS from another manufacturer and the issue is gone. I highly suspect that's the case for u too, hence the @
https://old.reddit.com/r/overclocking/comments/zkrofg/a_guide_to_overclocking_the_lenovo_legion_5_on/

**Comment by youmukonpaku1337** [comment] 2023-10-14 15:00
nope. my vbios is 130w, highest for this card
