### ISSUE TITLE
Feature request: Show the current display server in use

### ISSUE THREAD

**Issue by FurtadoPires** [flightlessmango/MangoHud#699] opened 2022-03-03 13:42 UTC
Would be possible for Mangohud to show which display server is being use for the game? Like "Wayland", "Xorg", "XWayland" or better yet, if it's possible to also show the version like "Mutter", "Kwin", "KwinFT", "Gamescope", "Xorg 21.1.3", "XWayland 21.1.3", etc...

This could be useful to show comparisons between how games perform in which one of those display servers, or for the user to be informed if the game is running through native Wayland or XWayland for example.

**Comment by rhysperry111** [comment] 2022-09-15 17:55
Semi-duplicate of #542

**Closed** 2023-06-23 18:36 UTC
