### ISSUE TITLE
Can't run mangohud on 32-bit games (Ubuntu)

### ISSUE THREAD

**Issue by nahuel3pro** [flightlessmango/MangoHud#611] opened 2021-10-07 00:30 UTC
Hi! I'm on ubuntu 20.04 and I can't get it work on 32bits games (windows or native). I get this log when trying lo launch a game in lutris (It doesn't work in any game there)

```
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
gamemodeauto: 
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
gamemodeauto: 
esync: up and running.

[2021-10-06 21:20:56.266] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/user/.config/MangoHud/wine-explorer.conf' [ not found ]
[2021-10-06 21:20:56.266] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/user/.local/share/lutris/runners/wine/lutris-6.1-3-x86_64/bin/MangoHud.conf' [ not found ]
[2021-10-06 21:20:56.266] [MANGOHUD] [info] [config.cpp:114] skipping config: '/home/user/.config/MangoHud/wine64-preloader.conf' [ not found ]
[2021-10-06 21:20:56.266] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/user/.config/MangoHud/MangoHud.conf'
```

I installed it through the ppa, any help? Thx

**Comment by Leopard1907** [comment] 2021-10-07 00:48
> I installed it through the ppa

Duplicate of [https://github.com/flightlessmango/MangoHud/issues/606](url)

Don't use PPA, use upstream binary package.

https://github.com/flightlessmango/MangoHud#github-releases

**Comment by ipkpjersi** [comment] 2022-03-03 15:38
You shouldn't need to build anything unless I'm missing something? The binary package has already compiled files.

**Closed** 2023-06-19 11:07 UTC
