### ISSUE TITLE
Seems new vulkan update broke compiling.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [flightlessmango/MangoHud#968] opened 2023-03-31 18:28 UTC
**Describe the bug**
Seems recent vulkan update broke compiling ? assuming.

https://hastebin.com/share/cefeqoxewe.yaml

**List relevant hardware/software information**
- Linux Distribution: Arch
- MangoHud version: git
- GPU

**To Reproduce**
compile via aur (yay)
See error

**Expected behavior**
Compiles

**Comment by jbeich** [comment] 2023-04-01 09:21
Duplicate of #927

**Comment by Edgars-Cirulis** [comment] 2023-04-01 09:24
> Duplicate of #927

Not really two different logs, I've looked if there's anything matching.

**Comment by jbeich** [comment] 2023-04-01 09:52
> Not really two different logs,

Try removing `-Duse_system_vulkan=enabled` e.g., from [mangohud-git PKGBUILD](https://github.com/archlinux/aur/blob/8d7c68307ebc/PKGBUILD#L31). CI passes because the option is `disabled` by default:
https://github.com/flightlessmango/MangoHud/blob/c037a0cca7b5f1c9d9948b0ff405778b10dcf0cd/meson_options.txt#L2

> I've looked if there's anything matching.

Clang and GCC have slightly different error style.

**Comment by jbeich** [comment] 2023-04-01 09:59
Note, your build log is very incomplete: neither AUR package name nor build flags are documented.

**Comment by Edgars-Cirulis** [comment] 2023-04-01 12:00
> 

Seems like mangohud-git is forcing to use system_vulkan.

**Closed** 2023-04-01 12:49 UTC
