### ISSUE TITLE
MangoHUD causes Resident Evil 4 Remake to crash if it is launched with Gamescope

### ISSUE THREAD

**Issue by DoomPenguin9** [flightlessmango/MangoHud#966] opened 2023-03-26 18:00 UTC
**Describe the bug**
If I launch the Resident Evil 4 Remake with gamescope and MangoHUD, the game crashes. MangoHUD works fine as long as the game is not launched with gamescope.

**List relevant hardware/software information**
- Arch Linux
- MangoHud  0.6.8.r125.g5d5df3d-1
- RX 7900 XTX
- Mesa 23.1.0-devel (git-879ddf9720)

**To Reproduce**
1. Go to the launch settings in Steam and set the launch options `mangohud gamescope -f -h 1440 -- %command%`
2. Launch the game
3. Game will proceed to crash.

**Expected behavior**
The game runs with MangoHUD showing in the top left corner.

**Comment by flightlessmango** [comment] 2023-03-26 18:16
Try setting `DXVK_FILTER_DEVICE_NAME=7900`

**Comment by DoomPenguin9** [comment] 2023-03-27 02:24
`DXVK_FILTER_DEVICE_NAME=7900` did not help. Also, RE4 remake is a DX12 game, how is a DXVK variable applicable here?

**Comment by gort818** [comment] 2023-03-27 03:00
I believe it has to do with dxgi.

I cannot reproduce as `mangohud gamescope -f -h 1440 -- %command%` runs fine on my 7900XTX on arch.

Do you have an iGPU?

**Comment by DoomPenguin9** [comment] 2023-03-27 16:48
> I believe it has to do with dxgi.
> 
> I cannot reproduce as `mangohud gamescope -f -h 1440 -- %command%` runs fine on my 7900XTX on arch.
> 
> Do you have an iGPU?

I do not have an iGPU.

**Comment by flightlessmango** [comment] 2023-03-27 18:43
Do you have multiple drivers installed? e.g mesa and amdgpu-pro for example?

**Comment by DoomPenguin9** [comment] 2023-03-27 19:41
> Do you have multiple drivers installed? e.g mesa and amdgpu-pro for example?

I do have AMDGPU-PRO and Mesa, but I have Mesa explicitly set as my default.

**Comment by gort818** [comment] 2023-03-27 21:33
Does removing amdgpu-pro help?

**Comment by DoomPenguin9** [comment] 2023-03-28 18:31
I does not help.

**Comment by DoomPenguin9** [comment] 2023-03-28 19:41
MangoApp works fine.

**Comment by flightlessmango** [comment] 2023-03-30 19:38
You don't want to attach mangohud to gamescope, but the to the game itself

**Comment by DoomPenguin9** [comment] 2023-04-01 08:18
> You don't want to attach mangohud to gamescope, but the to the game itself

How would I do that? Is it something like
```
gamescope -f -h 1440 -- bash -c " mangohud gamemoderun %command%"
```
If so, I just tried that, and it results in the same crash.

**Comment by MatthiasGrandl** [comment] 2023-04-05 14:43
i experience the same crash on a 7900XT

**Comment by gort818** [comment] 2023-04-05 17:29
I think it should be like this
`gamescope  -h 1440 -f -- mangohud %command%`

maybe try building gamescope from git

**Comment by jackun** [comment] 2023-04-05 19:37
You maybe need to "fake" enable vkBasalt

**Comment by Billli11** [comment] 2023-04-14 14:11
Can reproduce the problem.

There are other game have this problem too.

Tested

- Project Wingman (crash)
- Resident Evil 4 Remake (crash)
- Ace Combat 7 (work)

With both game that crash,

running mangohud both inside or outside gamescope produce the game result.

But only using `mangohud` script cause crashes. So may be `LD_PRELOAD` is the problem?

there are also a error message in stderr

    \re4.exe: ../mangohud/subprojects/imgui-1.81/imgui.cpp:7056: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed.

**Comment by gort818** [comment] 2023-04-14 15:12
@Billli11 Are you saying it works fine with gamescope, but using `mangohud` without gamescope crashes?

**Comment by Billli11** [comment] 2023-04-14 15:35
@gort818

No, if running both mangohud and gamescope the game will crash. If running only gamescope or mangohud the game wont crash.

If using environment variable `MANGOHUD=1`. Both with or without gamescope the game won't crash

**Comment by flightlessmango** [comment] 2023-06-10 21:03
> `gamescope -- sh -c "mangoapp & %command%"` --> didn't crash

This is the correct way to use mangohud with gamescope. Resolving the other crashes would just be to disable mangohud in those instances.
In other words it's out of scope to use any other method and as such not a bug

**Closed by flightlessmango** 2023-06-10 21:03 UTC
