### ISSUE TITLE
Not dispaly cpu temp in core 2 quad cpu

### ISSUE THREAD

**Issue by utherbone** [flightlessmango/MangoHud#203] opened 2020-06-08 03:41 UTC
Open this new issue because it was not resolved, I ended up taking too long to answer because I ended up not playing this period since the last issue I participated in, here https://github.com/flightlessmango/MangoHud/issues/147 what can I do to help you dev's to help me solve this problem?

I will repeat some commands that were requested from the last issue

**Command**: sensors
```
atk0110-acpi-0
Adapter: ACPI interface
Vcore Voltage:        1.36 V  (min =  +0.85 V, max =  +1.60 V)
 +3.3 Voltage:        3.12 V  (min =  +2.97 V, max =  +3.63 V)
 +5 Voltage:          4.78 V  (min =  +4.50 V, max =  +5.50 V)
 +12 Voltage:        11.82 V  (min = +10.20 V, max = +13.80 V)
SB Voltage:           1.07 V  (min =  +0.90 V, max =  +1.29 V)
SB2 Voltage:          1.65 V  (min =  +1.22 V, max =  +1.82 V)
FSBT Voltage:         1.39 V  (min =  +1.00 V, max =  +1.48 V)
DRAM Voltage:         2.24 V  (min =  +1.50 V, max =  +2.28 V)
DRAM Ref Voltage:     1.12 V  (min =  +0.75 V, max =  +1.14 V)
NB Voltage:           1.58 V  (min =  +1.04 V, max =  +1.56 V)
CPU FAN Speed:      1205 RPM  (min =  600 RPM, max = 7200 RPM)
CHASSIS1 FAN Speed: 2109 RPM  (min =  600 RPM, max = 7200 RPM)
CHASSIS2 FAN Speed: 1591 RPM  (min =  600 RPM, max = 7200 RPM)
CHASSIS3 FAN Speed: 2565 RPM  (min = 1800 RPM, max = 7200 RPM)
PWR FAN Speed:         0 RPM  (min = 1800 RPM, max = 7200 RPM)
OPT_Fan1 FAN Speed: 2636 RPM  (min =  800 RPM, max = 7200 RPM)
OPT_Fan2 FAN Speed:    0 RPM  (min =  800 RPM, max = 7200 RPM)
OPT_Fan3 FAN Speed:    0 RPM  (min =  800 RPM, max = 7200 RPM)
CPU Temperature:     +49.0°C  (high = +35.0°C, crit = +90.0°C)
MB Temperature:      +43.0°C  (high = +30.0°C, crit = +90.0°C)
NB Temperature:      +54.0°C  (high = +45.0°C, crit = +95.0°C)
SB Temperature:      +38.0°C  (high = +45.0°C, crit = +95.0°C)
OPT1 Temperature:     +0.0°C  (high = +45.0°C, crit = +95.0°C)
OPT2 Temperature:     +0.0°C  (high = +45.0°C, crit = +95.0°C)
OPT3 Temperature:     +0.0°C  (high = +45.0°C, crit = +95.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +63.0°C  (high = +76.0°C, crit = +100.0°C)
Core 1:       +56.0°C  (high = +76.0°C, crit = +100.0°C)
Core 2:       +68.0°C  (high = +76.0°C, crit = +100.0°C)
Core 3:       +62.0°C  (high = +76.0°C, crit = +100.0°C)
```
**Command**: cat /sys/class/hwmon/hwmon*/name
```
atk0110
coretemp
```
**Command**: ls /sys/class/hwmon/hwmon*/*_input
```
/sys/class/hwmon/hwmon0/fan1_input  /sys/class/hwmon/hwmon0/fan6_input  /sys/class/hwmon/hwmon0/in2_input  /sys/class/hwmon/hwmon0/in7_input    /sys/class/hwmon/hwmon0/temp3_input  /sys/class/hwmon/hwmon1/temp2_input
/sys/class/hwmon/hwmon0/fan2_input  /sys/class/hwmon/hwmon0/fan7_input  /sys/class/hwmon/hwmon0/in3_input  /sys/class/hwmon/hwmon0/in8_input    /sys/class/hwmon/hwmon0/temp4_input  /sys/class/hwmon/hwmon1/temp3_input
/sys/class/hwmon/hwmon0/fan3_input  /sys/class/hwmon/hwmon0/fan8_input  /sys/class/hwmon/hwmon0/in4_input  /sys/class/hwmon/hwmon0/in9_input    /sys/class/hwmon/hwmon0/temp5_input  /sys/class/hwmon/hwmon1/temp4_input
/sys/class/hwmon/hwmon0/fan4_input  /sys/class/hwmon/hwmon0/in0_input   /sys/class/hwmon/hwmon0/in5_input  /sys/class/hwmon/hwmon0/temp1_input  /sys/class/hwmon/hwmon0/temp6_input  /sys/class/hwmon/hwmon1/temp5_input
/sys/class/hwmon/hwmon0/fan5_input  /sys/class/hwmon/hwmon0/in1_input   /sys/class/hwmon/hwmon0/in6_input  /sys/class/hwmon/hwmon0/temp2_input  /sys/class/hwmon/hwmon0/temp7_input
```
One thing I didn’t site is that my motherboard your MCH (chipset) is the Intel x48 and the motherboard has sensors mirrored by the board, it’s an Asus Rampage Formula

To run the game in steam I use this parameter:  `MANGOHUD=1 MANGOHUD_CONFIG=full %command%`

I forgot to mention that I am now using the latest version of the mangohud that I have compiled.

**Comment by flightlessmango** [comment] 2020-06-08 03:44
It displays no temp at all or it's an incorrect one?

**Comment by utherbone** [comment] 2020-06-08 03:49
![mangohud](https://user-images.githubusercontent.com/13210391/83990978-bee64b80-a921-11ea-99ad-12cc1dc3574d.png)
A print I just took from a game I play.

**Comment by rtentser** [comment] 2020-06-08 11:50
Updating to git master solved a problem for me (some days ago).

But today i've installed a new fan and noticed that cpu_temp in mangohud and in sensors are different. Mangohud shows less than 40, while sensors — more then 50. Do i need to create new issue for that?

**Comment by utherbone** [comment] 2020-06-09 15:21
@rtentser have to check if the temperatures of the sensors are of the cores, because the cpu temp is the temperature of the IHS of the metallic part of the top of the processor. The core tem is always higher as far as I know.
Any news @flightlessmango?

**Comment by jackun** [comment] 2020-06-09 15:28
It looks for `Package id 0` in temp*_label, maybe it's something different?

**Comment by rtentser** [comment] 2020-06-09 15:35
> have to check if the temperatures of the sensors are of the cores
Yes, the cores. So, it's not a bug, good. Thank you, @utherbone.

**Comment by utherbone** [comment] 2020-06-10 03:06
> It looks for `Package id 0` in `temp*_label`, maybe it's something different?
> e: nope
I can't say. excuse me. If you want I can test some solution contact me just ask that I send my contact, Telegram or Discord.

**Comment by flightlessmango** [comment] 2020-06-11 09:36
MangoHud is looking for `Package id 0` when it's `coretemp`, according to your paste you don't have that one. I'm only seeing core temps, no overall temp

**Comment by flightlessmango** [comment] 2020-06-12 02:23
A fix for this was added in 0.4.1, needs testing

**Comment by utherbone** [comment] 2020-06-13 17:03
@flightlessmango it worked perfectly, I see the same temperature as in the "sensors" I am sorry I cannot make any financial donation.
But I will support in another way when I helped the @rtentser by solving a doubt about it.
![manguhud_work_cpu_temp](https://user-images.githubusercontent.com/13210391/84574646-2b2bd980-ad7e-11ea-96bc-16633da9a02e.png)

**Comment by rtentser** [comment] 2020-06-15 07:29
Yes, looks like the difference was fixed, thank you!

**Comment by flightlessmango** [comment] 2020-06-15 07:37
Closing as it's solved

**Closed by flightlessmango** 2020-06-15 07:37 UTC
