### ISSUE TITLE
Doesn't work on all games I use with Proton Version 5.13-2

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#396] opened 2020-11-15 13:33 UTC
I don't know if that's more a issues of Mangohud or Proton.
For every Game that uses Proton Version 5.15-2 it doesn't work,but all games with lower versions of Proton it works.

**Comment by flgx16** [comment] 2020-11-15 13:41
Duplicate of #369

**Closed** 2020-11-15 13:43 UTC

**Comment by Toadfield** [comment] 2020-11-15 14:56
ok
