### ISSUE TITLE
Lutris MangoHud wont show GPU Stats in HUD configured with Goverlay

### ISSUE THREAD

**Issue by Draguljche** [flightlessmango/MangoHud#505] opened 2021-03-26 23:25 UTC
Hello, can someone help me with this issue, onlu GPU stats wont show mangohud? 

My GPU is Nvidia GTX1080 with non-free driver. Im on Debian Sid.

**Comment by vesterlay** [comment] 2021-04-03 04:04
Is that by any means duplicate of #499, try to run `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libnvidia-ml1:i386 libnvidia-ml1`

**Comment by Draguljche** [comment] 2021-04-04 00:11
> Is that by any means duplicate of #499, try to run `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libnvidia-ml1:i386 libnvidia-ml1`

Well big THANK YOU. it worked perfectly well.

**Closed** 2021-04-15 13:21 UTC
