### ISSUE TITLE
geforce gtx 1050 power draw is dont detected

### ISSUE THREAD

**Issue by mrdeathjr28** [flightlessmango/MangoHud#296] opened 2020-07-25 17:36 UTC
hi

geforce gtx 1050 power draw is dont detected

however i use this command in console for detect power draw:

nvidia-smi stats -i 0 -d pwrDraw

**Comment by jackun** [comment] 2020-09-27 15:12
Duplicate of #291

Closing for clean up.

**Closed by jackun** 2020-09-27 15:12 UTC
