### ISSUE TITLE
Option to set number of frames shown in graph/histogram

### ISSUE THREAD

**Issue by CyberShadow** [flightlessmango/MangoHud#723] opened 2022-04-03 21:59 UTC
Currently this is a static array:

https://github.com/flightlessmango/MangoHud/blob/425b98ae9a21b672d2e50338b52ef7efbe384b91/src/overlay.h#L59

Graphs are then drawn using `ARRAY_SIZE` of that array.

Would be nice if this limit was configurable instead of hard-coded to 200.

Use case: I'm trying to visually demonstrate a performance issue which manifests as stable high FPS -> ~5 seconds of unstable FPS -> stable low FPS.

**Comment by flightlessmango** [comment] 2023-11-12 04:05
closing as duplicate of #700

**Closed by flightlessmango** 2023-11-12 04:05 UTC
