### ISSUE TITLE
Games launched with Proton-5.9-GE-8-ST and mangohud never actually start

### ISSUE THREAD

**Issue by Nano-Ocelot** [flightlessmango/MangoHud#382] opened 2020-11-07 07:13 UTC
OpenSUSE Tumbleweed
Proton-5.9-GE-8-ST

When starting a game that uses vulkan with 'mangohud' in the steam launch options, the game never actually appears. Games appear to launch fine using mangohud with Proton 5.0-10, however that's not an option with all games and isn't preferable for any game because I can't alt-tab without 'blacking out' the game window when using 5.0-10.

Here is the output from terminal 

```
Opted-in Controller Mask for AppId 1190460: fffc
Loaded Config for Local Selection Path for App ID 1190460, Controller 4294967295: /home/Rylee/.local/share/Steam/steamapps/workshop/content/241100/2088964324/1027328544664640371_legacy.bin
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: enabling seccomp syscall filters.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: enabling seccomp syscall filters.
wine: enabling seccomp syscall filters.
wine: enabling seccomp syscall filters.
wine: enabling seccomp syscall filters.
wine: enabling seccomp syscall filters.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1190460, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 1190460, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 1190460 "", ProcID 23910, IP 0.0.0.0:0
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Starting app 1190460
Loaded Config for Local Selection Path for App ID 1190460, Controller 4294967295: /home/Rylee/.local/share/Steam/steamapps/workshop/content/241100/2088964324/1027328544664640371_legacy.bin
>>> Adding process 23910 for game ID 1190460
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 23911 for game ID 1190460
GameAction [AppID 1190460, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
ProtonFixes[23911] INFO: Running protonfixes
ProtonFixes[23911] INFO: Running checks
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ProtonFixes[23911] INFO: All checks successful
ProtonFixes[23911] INFO: Using global defaults for "DEATH STRANDING" (1190460)
ProtonFixes[23911] INFO: No protonfix found for "DEATH STRANDING" (1190460)
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 23924 for game ID 1190460
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
gamemodeauto: 
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
esync: up and running.
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 23926 for game ID 1190460
wine: enabling seccomp syscall filters.
>>> Adding process 23927 for game ID 1190460
>>> Adding process 23930 for game ID 1190460
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: enabling seccomp syscall filters.
>>> Adding process 23933 for game ID 1190460
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: enabling seccomp syscall filters.
>>> Adding process 23936 for game ID 1190460
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: enabling seccomp syscall filters.
>>> Adding process 23944 for game ID 1190460
ERROR: ld.so: object '/home/Rylee/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
wine: enabling seccomp syscall filters.
>>> Adding process 23979 for game ID 1190460
wine: enabling seccomp syscall filters.
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
skipping config: /home/Rylee/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/Rylee/.local/share/Steam/compatibilitytools.d/Proton-5.9-GE-8-ST/dist/bin/MangoHud.conf [ not found ]
skipping config: /home/Rylee/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/Rylee/.config/MangoHud/MangoHud.conf [ ok ]
```

**Comment by Joan31** [comment] 2020-11-09 23:36
Same problem with Proton 5.13-1 and example Skyrim, Dying Light etc...
But with Proton 4 it is ok.

**Comment by flightlessmango** [comment] 2020-11-10 00:17
@Joan31 your issue is probably #369

**Comment by sonic2kk** [comment] 2020-11-10 22:26
FWIW all versions of Proton-5.9-GE work perfectly fine for me - Proton 5.13-1 doesn't work (have not tried 5.13-2).  In the meantime, you could use [Proton-tkg 5.21](https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.21.r0.ge2d9f97b), which works fine for me. I actually tested a few different versions of Proton to see why it wasn't working and came across this issue and numerous others when I was doing research before filing an issue!

Not sure why it works with Proton-GE for me but not others...

**Comment by Nano-Ocelot** [comment] 2020-11-11 02:04
> FWIW all versions of Proton-5.9-GE work perfectly fine for me - Proton 5.13-1 doesn't work (have not tried 5.13-2). In the meantime, you could use [Proton-tkg 5.21](https://github.com/Frogging-Family/wine-tkg-git/releases/tag/5.21.r0.ge2d9f97b), which works fine for me. I actually tested a few different versions of Proton to see why it wasn't working and came across this issue and numerous others when I was doing research before filing an issue!

Proton-tkg-5.21 doesn't work with mangohud for me either. Thanks for the suggestion though.

**Comment by flightlessmango** [comment] 2020-11-11 02:12
@Nano-Ocelot does mangohud work in any instance?

**Comment by Nano-Ocelot** [comment] 2020-11-11 02:40
Like the original post says, it works fine with official 5.0-10.

**Comment by gort818** [comment] 2020-11-11 04:44
Can you try removing gtk3-nocsd?

**Comment by Nano-Ocelot** [comment] 2020-11-11 05:57
I just tried that and it doesn't make a difference. Both proton-tkg and proton-ge still won't work with mangohud.

**Comment by Yowlen** [comment] 2020-11-17 17:01
I've found that MangoHud appears to somehow corrupt itself every once in a while (or maybe some system update removes symlinks or something), causing problems where this would happen. Reinstalling MangoHud using the original installer (which will preserve the local config file, so nothing needs to be changed config-wise) will fix this issue so that the game itself can actually start.

(Whether or not MangoHud itself works depends on other factors from the Proton version itself that are already addressed in other bug reports.)

I never really got around to narrowing down the cause, but I can confirm that as long as the game works without MangoHud, they'll also run with it after reinstalling MangoHud, even if other bugs from Proton may prevent MangoHud itself from working.

**Comment by flightlessmango** [comment] 2020-11-17 21:01
@Yowlen check if setting `NODEVICE_SELECT=1` works

**Comment by Nano-Ocelot** [comment] 2020-11-22 05:28
After some more investigating it turns out it was the package that I was using from a 3rd party repo. I tried the official release from this github and it works now.

**Closed** 2021-02-01 10:40 UTC
