### ISSUE TITLE
manghud crashes steam  overlay when using `exec` option

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#639] opened 2021-11-28 03:33 UTC
running a steam game (any game have tried several including a hat in time , edge of eternity, shadow of the tomb raider and trails of cold steel) with mango hud passed in the launch command will cause steam to crash randomly when opening steam overlay (can make it happen more consistent by toggling the steam input overlay option which overlays stick movements on top) 

steps to reproduce:
1. open any steam game with mangohud enabled
2. accses the steam overlay with the guide button after playing for a few minutes
3. if it doesn't crash right away try toggling the steam input overlay option

logs and crash dumps: https://drive.google.com/file/d/1-BsRWAi4J0cS4sq3PVR3qNohArkE1dCY/view?usp=sharing

sys info: https://linux-hardware.org/?probe=0b1d816eff

**Comment by zany130** [comment] 2021-12-01 00:47
Using DXVK HUD does not cause this issue in any of the aforementioned games. Both dxvk HUD and mango where Lauched through steam launch commands

also something i noticed Mangohud overlays on top of the steam overlay while DXVK HUD does not

**Comment by zany130** [comment] 2021-12-01 22:44
Crash is not reproducible in older versions (Test 0.5.1)

**Comment by RobotRoss** [comment] 2021-12-02 15:09
I've also had this, although it seems to be unrelated to the use of the Steam Overlay, Mangohud will just cause Steam to crash randomly after x amount of time (it doesn't seem to be a specific amount of time, but uninstalling MangoHUD will stop Steam from crashing in-game)

**Comment by zany130** [comment] 2021-12-02 22:43
> I've also had this, although it seems to be unrelated to the use of the Steam Overlay, Mangohud will just cause Steam to crash randomly after x amount of time (it doesn't seem to be a specific amount of time, but uninstalling MangoHUD will stop Steam from crashing in-game)

it only happens to me when I open the steam overlay also been using 0.6.4 for a while now and no crashes switched to the latest git and I got a crash after play for about 20 min and opening the steam overlay

**Comment by cinderofsouls** [comment] 2021-12-04 01:20
> I've also had this, although it seems to be unrelated to the use of the Steam Overlay, Mangohud will just cause Steam to crash randomly after x amount of time (it doesn't seem to be a specific amount of time, but uninstalling MangoHUD will stop Steam from crashing in-game)

Same for me, steam crashes after 15-30 minutes only while mangohud is active. I've just done a clean install of endeavour os with very little else installed and it's still a problem. I can provide logs or whatever if needed, but I'm still relatively new to this so I'll need to know exactly what to look for.

**Comment by zany130** [comment] 2021-12-04 01:38
@cinderofsouls  @RobotRoss 
Did you both try this version https://github.com/flightlessmango/MangoHud/releases/tag/v0.6.4

Any newer than that and i get crashes but with that version i get 0 crashes. This would be useful to confirm that it really is a regression in newer versions and not something specific to my machine

You can install that version by uninstalling the version you currently have, extracting that archive, and running the setup file in a terminal

**Comment by cinderofsouls** [comment] 2021-12-04 01:49
I tried both 0.6.4 and 0.5.1 after reading your comment the other day and still got crashes on both of them unfortunately. I also haven't seen any relation to the steam overlay, so it sounds like whatever I have is closer to @RobotRoss than yours.

**Comment by RobotRoss** [comment] 2021-12-04 11:36
The version I was using was 0.6.6 - My distro is Fedora 35.

**Comment by cinderofsouls** [comment] 2021-12-04 23:08
> Crash is not reproducible in older versions (Tested 0.5.1 and 0.6.4) 0.6.5 does crash however

@zany130 How extensively have you tested older versions? I was able to play for around 3 hours before crashing on one of my tests on 0.5.1

**Comment by zany130** [comment] 2021-12-04 23:10
> > Crash is not reproducible in older versions (Tested 0.5.1 and 0.6.4) 0.6.5 does crash however
> 
> @zany130 How extensively have you tested older versions? I was able to play for around 3 hours before crashing on one of my tests on 0.5.1

well I played for about 4 hours with no issue on 6.4 yesterday but I just got a crash now in 6.4 after playing for about 30 mins and then opening the overlay to check something

**Comment by cinderofsouls** [comment] 2021-12-04 23:27
When would that be generated? I'm getting `No coredumps found.`

Also, what does your mangohud config look like? I can't seem to find it again now, but I saw some reddit thread earlier on a similar issue saying that having a more minimal config with just something like fps, gpu usage and temp would be fine but a fully loaded config would cause the crashes. I'm currently using the "full" preset from GOverlay, so definitely fully loaded with everything.

Of course not using all the things isn't really a solution, but maybe it helps narrow down the problem.

**Comment by zany130** [comment] 2021-12-04 23:35
this is my config https://hastebin.com/emaheciqic so yeah its not minimal . as for the coredumps steam should make a coredump when it crashes  and then you can use `coredumpctl info steam` to read it  just `coredumpctl` should list all the coredumps on your system

**Comment by cinderofsouls** [comment] 2021-12-04 23:45
Just crashed with the steam overlay disabled in the settings. Still getting `No coredumps found.` from `coredumpctl info steam` strangely. Running `coredumpctl` and the only steam related thing there is the path to wine64-preloader under proton experimental. 

I know that's not what I'm looking for, but I'm looking at it anyway and there is a lot here. When you say "ends in", do you mean the stack trace or something else?

**Comment by zany130** [comment] 2021-12-04 23:49
yeah the stack trace for example this is how mine looks https://hastebin.com/apogefenak
though I don't know why steam isn't producing a coredump.

Are you sure its steam thats crashing and not just the game?

for me steam AND the game crash and I have to go and open steam again and it gives me a message about it uploading the crashlog

**Comment by cinderofsouls** [comment] 2021-12-04 23:55
I'm sure steam is crashing, and I have to log in again afterwards. It hasn't ever prompted me about a crash log though. 
I'll get some "disconnected from the network" message ingame, then I'll look over and see that steam is no longer open. 5 to 10 seconds later and the game also either freezes or crashes.

**Comment by zany130** [comment] 2021-12-05 00:07
idk then it sounds like steam isn't creating a crashdump in your case. also If i disable the steamoverlay or never accses it my game(s) never crash its only when I pull up the steam bigpicture overlay ( i use big picture with a controller) that I get a crash obviously disabling the steam overlay is not a solution for me as that also disables controller support

**Comment by cinderofsouls** [comment] 2021-12-05 00:16
I don't currently have the bandwidth to download and test a bunch of different games for now unfortunately. The only game I've managed to get mangohud to work at all on so far is Sekiro, my others either won't launch or just wont display the hud

But yes, it sounds like we probably have different problems so I'll probably have to create my own issue here once I figure out how to get all the logs and dumps I need

**Comment by cinderofsouls** [comment] 2021-12-05 07:28
I'm currently thinking that whatever the issue is is caused by something in the config file. I've just been using the default "full" config from GOverlay, and it definitely has some things that I consider unnecessary and that I can see being more likely to break than the standard basic sensors. I'm doing some testing with stripping it down a little, trying to see if the crashes are related to any particular settings or if they're possibly related to the total number of settings there. It's not a lot to go on, but I have next to nothing else to try and it lines up with that reddit thread I mentioned a few comments ago.

Maybe you'd consider trying the same thing if you have time to spare. It takes a quite a a while to test these crashes as you know, so I'll be here for a long time if I'm on my own with this lol

**Comment by zany130** [comment] 2021-12-05 21:10
honestly this would be pretty hard to fix like @flightlessmango said on discord when 1.we cant reliably get the game to crash within a reasonable amount of time 2. not even sure what is causing the crash mine seems to be the steam overlay as that's the only time it crashes but we don't know about the others. for example I said yesterday I got a crash on 6.4 but I haven't gotten a crash since so I don't know it could be because I did a clean reinstall (completely removed mangohud from my system and then rebuilt using the PKGBUILD for 6.4 from the aur page archives) I do know on the latest git and 6.6 I get the crashes way more often

**Comment by zany130** [comment] 2021-12-07 21:18
tested all of yesterday and today and haven't gotten a single crash after uncommenting the `exec` option in the config so I'm 90% sure that is what is causing the crash

**Comment by flightlessmango** [comment] 2021-12-09 20:18
My assumption is that the exec function has been leaking memory, I've updated this function in hopes to address that. f2dcf3f4b24de9b98c0668b961001556ff53dee8
Please try this commit / latest master and report back if crashing still occurs

**Comment by zany130** [comment] 2021-12-11 23:16
still crahsing on version : `0.6.6.1.r16.ge7de7b5-1` from the chaoticaur

**Comment by zany130** [comment] 2021-12-22 02:22
seems like my issues is fully fixed  with this commit https://github.com/flightlessmango/MangoHud/commit/aab8730f69ba16b95d542650ab489e7b05d2d88d don't know if @cinderofsouls and @RobotRoss are still having the issue though

**Comment by flightlessmango** [comment] 2021-12-28 05:51
closing as it seems to be fixed

**Closed by flightlessmango** 2021-12-28 05:51 UTC
