### ISSUE TITLE
Doesn't Display With New Proton 5.13

### ISSUE THREAD

**Issue by mister-x123** [flightlessmango/MangoHud#370] opened 2020-10-16 11:35 UTC
As title says. Works on all other Proton versions, but not the new one. Needs an update/fix

**Comment by Leopard1907** [comment] 2020-10-16 11:47
Duplicate of https://github.com/flightlessmango/MangoHud/issues/369

That is an issue caused by Steam's Soldier runtime which Proton 5.13 relies on. Fix should be coming from Valve's side , not Mangohud.

Other layers such as Vkbasalt, libstrangle etc also doesn't work currently on this Proton version.

Please check the issue tracker of Mangohud before opening a new one to see if there is already a report about your issue.

**Comment by Galcian79** [comment] 2020-10-16 20:21
> Duplicate of #369
> 
> That is an issue caused by Steam's Soldier runtime which Proton 5.13 relies on. Fix should be coming from Valve's side , not Mangohud.
> 
> Other layers such as Vkbasalt, libstrangle etc also doesn't work currently on this Proton version.
> 
> Please check the issue tracker of Mangohud before opening a new one to see if there is already a report about your issue.

I can confirm it works fine with new proton and vulkan games, so this is definitely not a mangohud issue.

**Comment by flightlessmango** [comment] 2020-10-16 21:56
Please continue this conversation in #369

**Closed by flightlessmango** 2020-10-16 21:56 UTC
