### ISSUE TITLE
Counter Strike 2 crashes with mangohud after latest CS2 update

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [flightlessmango/MangoHud#1139] opened 2023-09-30 07:46 UTC
**Describe the bug**
MangoHUD works within the menus, but trying to load into a game causes a crash

`/redacted/steamapps/common/Counter-Strike Global Offensive/game/cs2.sh: line 115: 20173 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

**List relevant hardware/software information**
OpenSUSE Tumbleweed 20230927
Linux 6.5.4
Mesa 23.1.8
R5 5600/RX 5700XT
MangoHUD 0.6.9 and 0.7.0

**To Reproduce**
Practice -> Casual -> Nuke -> Play

**Comment by daxcore** [comment] 2023-09-30 12:28
@rKsanu2MMYvypWePtQWM refer readme file: 

> Or alternatively, add MANGOHUD=1 to your shell profile (Vulkan only).

that works for me.

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2023-09-30 17:11
Can confirm this works as a workaround

**Comment by gort818** [comment] 2023-09-30 21:32
Cannot reproduce this on Arch with a 7900xtx

**Comment by gort818** [comment] 2023-10-05 04:19
Is this still an issue?

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2023-10-05 08:18
> Is this still an issue?

will test later today

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2023-10-05 17:29
> Is this still an issue?

Yes, `mangohud %command%` still crashes the game while the environment variable method works just fine.

**Comment by flightlessmango** [comment] 2023-10-05 17:49
I'm wondering if there's remnants of 0.6.9 still on the system as these symptoms existed in 0.6.9 and was fixed in 0.7

**Comment by Keplyx** [comment] 2023-10-06 09:17
On my end it only crashes on the nuke map if using `mangohud %command%` launch option. Other maps work fine.

The crash is fixed when using `MANGOHUD=1 %command%` launch option.

Crash happens on both 0.6.9 and 0.7.0

**Comment by Leopard1907** [comment] 2023-10-06 09:59
I've tested with Nuke map, no crashes.

`mangohud %command%`

Master, rdna 3 gpu, Mesa 23.2.1

**Comment by Keplyx** [comment] 2023-10-06 15:11
I'm not 100% sure but I think it worked on nuke a few days ago. But now it only crashes for nuke on my end.

**Comment by itz-me-zappex** [comment] 2023-10-07 16:00
I can reproduce this issue.

Distro: Arch Linux (updated a few hours ago)
GPU: NVIDIA GeForce GTX 1050 Ti
Driver: 535.113.01 (nvidia-dkms)
Kernel: 6.5.4-273-tkg-eevdf (linux65-tkg-eevdf)
Mangohud version: 0.7.0 (mangohud-0.7.0-1)

Video:
https://github.com/flightlessmango/MangoHud/assets/85901674/21499da2-c93a-41c5-9e8b-273e2563074c

**Comment by flightlessmango** [comment] 2023-10-07 19:49
A gdb backtrace could be useful.
Uninstall any mangohud version you have now
Compile and install mangohud with debug symbols
`./build.sh clean build_dbg install`
Start the game
In a terminal attach gdb
```gdb -p `pgrep cs2 | tail -n1` ```
The game should now freeze
Type `continue` in gdb
Game unfreezes
Reproduce the crash
Then type `bt full` in gdb and paste the output here

**Comment by flightlessmango** [comment] 2023-10-08 01:56
The issue appears to be caused by a newer version of spdlog. On arch the issue can be resolved by using the subproject instead of system spdlog

**Comment by serebit** [comment] 2023-10-09 16:24
@flightlessmango you should ping me next time :) I'm on it

**Comment by rKsanu2MMYvypWePtQWM** [comment] 2023-10-09 17:04
What about OpenSUSE?

**Comment by flightlessmango** [comment] 2023-10-10 02:01
@serebit Nice! I didn't consider this should/could be handled downstream.

@rKsanu2MMYvypWePtQWM We need to contact the maintainer and have them do the same thing or wait for the next mangohud release

**Comment by serebit** [comment] 2023-10-10 02:31
> @serebit Nice! I didn't consider this should/could be handled downstream.

Obviously I'd still like the issue to be fixed in main so I can apply a patch to 0.7.0 instead of using the vendored version of spdlog, but it's still better to apply an immediate workaround instead of letting mangohud's Arch package stay broken until that happens.

**Comment by flightlessmango** [comment] 2023-10-10 03:28
@serebit Yeah absolutely, it looks like we have a fix now 30c7755.
I'm unable to repro it anymore so hopefully someone else can confirm

**Comment by flightlessmango** [comment] 2023-10-10 04:34
Still crashing, no fix yet

**Comment by gort818** [comment] 2023-10-12 15:56
So the issue is reproducible when using spdlog built with `external_fmt`. I haven't been able to track down exactly where the issue lies. So far as we know the only game that has the issue is CS2 and no luck finding out why.

**Comment by gort818** [comment] 2023-10-18 23:14
For anyone still having this issue, go to your cs2 installation folder  and edit cs2.sh`steamapps/common/Counter-Strike Global Offensive/game/cs2.h`

and add `unset LD_PRELOAD` after `#!/bin/bash`

**Comment by gort818** [comment] 2023-10-21 00:42
This should be fixed in latest master

**Comment by gort818** [comment] 2024-02-09 17:30
Fixed in latest release v0.7.1

**Closed by gort818** 2024-02-09 17:30 UTC

**Comment by kariif** [comment] 2024-05-07 17:55
> Fixed in latest release v0.7.1

its still crashing for me

**Comment by flightlessmango** [comment] 2024-05-07 19:36
> its still crashing for me

@kariif in the exact same way as was reported initially in this issue?

**Comment by feer9** [comment] 2025-01-21 23:09
> > its still crashing for me
> 
> [@kariif](https://github.com/kariif) in the exact same way as was reported initially in this issue?

it's crashing for me, both with `mangohud %command%`  and `MANGOHUD=1 %command%`.

The crash line is this, I think it's the same as reported initially

`SteamLibrary/steamapps/common/Counter-Strike Global Offensive/game/cs2.sh: line 98: 94085 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

I don't know how to get more info
