### ISSUE TITLE
Doesen't work in CSGO and TF2

### ISSUE THREAD

**Issue by Ohio2** [flightlessmango/MangoHud#362] opened 2020-10-04 12:31 UTC
**So... i don't know how this fails to work... but it doesen't**
OS: Arch Linux x86_64 
Host: Precision T1500 00 
Kernel: 5.8.13-zen1-2-zen 
Uptime: 3 hours, 1 min 
Packages: 1409 (pacman) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: Plasma 
WM: KWin 
Theme: Breeze Dark [Plasma], Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: MesloLGS NF 9 
CPU: Intel i5 750 (4) @ 2.548GHz 
GPU: NVIDIA GeForce GTX 1050 
Memory: 2753MiB / 15968MiB 
------------------------------
_Installed with yet another yogurt_ (YAY)

**Comment by jackun** [comment] 2020-10-04 12:45
Duplicate of #339

**Closed by jackun** 2020-10-04 12:45 UTC
